version: '3'

services:
  web:
    image : nginx:latest
    container_name: web
    hostname : web
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/var/www/html
      - ../certif:/etc/ssl
    networks:
      - web
  db:
    image: mariadb
    container_name: db
    hostname: db
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db
  php:
    build: ./php
    image: php
    container_name: php
    hostname: php
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${PHP_USER}
      DB_PASSWORD: ${PHP_PASSWORD}
      DB_HOST: ${PHP_HOST}
    volumes:
      - ./html:/var/www/html
    networks:
      - web
      - db
networks:
  web:
  db:
