version: '3'

services:
  web:
    image : nginx:latest
    container_name: web
    hostname : web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/var/www/html
    restart: always
  db:
    image: mariadb
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: user
      MYSQL_PASSWORD: mypass
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
  php:
    image: php
    container_name: php
    hostname: php
    volumes:
      - ./html:/var/www/html
